services:
  # Nginx
  nginx:
    image: nginx:latest
    container_name: study-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  # PHP 8.3
  php:
    build:
      context:    ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: study-php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  cli:
    restart:        'no'
    build:
      context:    ./docker/php-cli
      dockerfile: Dockerfile
    container_name: study-php-cli
    command:        composer install --ignore-platform-reqs --no-scripts --no-progress
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  # PostgreSQL 16
  postgres:
    image: postgres:16
    container_name: study-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - app-network

  # Redis
  redis:
    image: redis:latest
    container_name: study-redis
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis-data:/data
    networks:
      - app-network

# Сети
networks:
  app-network:
    driver: bridge
